# -*- coding: utf-8 -*-
"""data_cleaning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wIwCeA1_x6OOSzbm0ZiIAQGGGkYXpX7e
"""

# BLOCK 1-IMPORTS & PATH SETUP

import pandas as pd
import numpy as np
from pathlib import Path
import json
import matplotlib.pyplot as plt

# Set file paths
DATA_DIR = Path("data")
RAW = DATA_DIR / "adult.csv"
CLEAN = DATA_DIR / "adult_clean.csv"
SENSITIVE = DATA_DIR / "adult_sensitive.csv"

RANDOM_STATE = 42

# BLOCK 2—LOAD RAW DATA & UNDERSTAND IT

RAW = "/content/adult.csv"
df = pd.read_csv(RAW, header=0, na_values=['?', ' ?', ''])

print("Initial Shape:", df.shape)
print("\nColumns:\n", df.columns.tolist())
print("\nMissing Values:\n", df.isna().sum())
print("\nSample Rows:\n", df.head())

# BLOCK 3-Data Exploration

for col in df.columns:
    print(f"Column: {col}")
    print(df[col].value_counts(dropna=False).head(10))

# BLOCK 4-CLEAN WHITESPACE + FIX TYPES

# Remove whitespace from object columns
obj_cols = df.select_dtypes(include="object").columns
for c in obj_cols:
    df[c] = df[c].astype(str).str.strip()
    df.loc[df[c] == "", c] = np.nan

# Convert numeric-able columns
numeric_expected = [
    "age", "fnlwgt", "education-num",
    "capital-gain", "capital-loss", "hours-per-week"]

for col in numeric_expected:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

# BLOCK 5-REMOVE DUPLICATES

before = len(df)
df = df.drop_duplicates().reset_index(drop=True)
after = len(df)

print(f"Duplicates removed: {before - after}")

# BLOCK 6-IMPUTE MISSING VALUES(fill with mode and median)

missing_before = df.isna().sum().sum()

numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = [c for c in df.columns if c not in numeric_cols]

# Numeric → median
for c in numeric_cols:
    df[c] = df[c].fillna(df[c].median())

# Categorical → mode
for c in cat_cols:
    mode = df[c].mode(dropna=True)
    df[c] = df[c].fillna(mode[0] if len(mode) > 0 else "Missing")

# Remaining missing → drop rows
remaining = df.isna().sum().sum()
rows_dropped = 0

if remaining > 0:
    before = len(df)
    df = df.dropna().reset_index(drop=True)
    after = len(df)
    rows_dropped = before - after

print("Missing before:", missing_before)
print("Rows dropped after imputation:", rows_dropped)

# BLOCK 7-TRANSFORM TARGET COLUMN(income → 0/1)

if "income" in df.columns:
    df["income"] = df["income"].apply(
        lambda x: 1 if str(x).startswith(">") else 0
    )
print(df["income"].value_counts())

# BLOCK 8-SAVE CLEANED DATASET

CLEAN = "/content/adult_clean.csv"   # ← FIXED PATH FOR COLAB

df.to_csv(CLEAN, index=False)

print("Saved clean dataset →", CLEAN)

# BLOCK 9-SAVE SENSITIVE ATTRIBUTES FILE FOR BIAS CHECKING

SENSITIVE = "/content/adult_sensitive.csv"   # ← FIXED PATH FOR COLAB

sensitive_cols = [c for c in ["sex", "race", "income"] if c in df.columns]

df[sensitive_cols].to_csv(SENSITIVE, index=False)

print("Saved sensitive data →", SENSITIVE)

# BLOCK 11 — STEP 4: ENCODE DATA (ONE-HOT ENCODING)

ENCODED = "/content/adult_encoded.csv"

# Perform one-hot encoding (drop_first=True to avoid duplicate multicollinearity)
df_encoded = pd.get_dummies(df, drop_first=True)

df_encoded.to_csv(ENCODED, index=False)

print("Saved encoded dataset →", ENCODED)

# BLOCK 13 — STEP 6: TRAIN / STREAM SPLIT

from sklearn.model_selection import train_test_split

TRAIN = "/content/train.csv"
STREAM = "/content/stream.csv"

train_df, stream_df = train_test_split(df_encoded, test_size=0.30, random_state=42)

train_df.to_csv(TRAIN, index=False)
stream_df.to_csv(STREAM, index=False)

print("Saved train dataset →", TRAIN)
print("Saved stream dataset →", STREAM)

